/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e3e0f1",
        "background": "#12121d",
        "on-primary-fixed-variant": "#42436b",
        "on-secondary": "#003919",
        "inverse-primary": "#5a5b84",
        "secondary": "#4ae183",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#00504a",
        "primary-fixed-dim": "#c2c2f2",
        "on-surface-variant": "#c8c5cf",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#005228",
        "surface-container-lowest": "#0d0d18",
        "outline-variant": "#47464e",
        "surface-tint": "#c2c2f2",
        "primary-fixed": "#e1e0ff",
        "on-tertiary": "#003733",
        "primary": "#c2c2f2",
        "surface-container-highest": "#343440",
        "secondary-fixed": "#6bfe9c",
        "tertiary": "#5adace",
        "surface": "#12121d",
        "on-primary-fixed": "#16173d",
        "surface-variant": "#343440",
        "tertiary-fixed-dim": "#5adace",
        "on-surface": "#e3e0f1",
        "on-primary": "#2b2d53",
        "surface-container": "#1f1e2a",
        "on-primary-container": "#8283af",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "inverse-on-surface": "#302f3b",
        "tertiary-container": "#002421",
        "secondary-container": "#06bb63",
        "secondary-fixed-dim": "#4ae183",
        "on-secondary-fixed": "#00210c",
        "surface-bright": "#383845",
        "surface-container-low": "#1b1a26",
        "on-tertiary-container": "#00978d",
        "surface-dim": "#12121d",
        "on-secondary-container": "#00431f",
        "outline": "#918f99",
        "on-tertiary-fixed": "#00201d",
        "surface-container-high": "#292935",
        "tertiary-fixed": "#79f7ea",
        "on-background": "#e3e0f1",
        "primary-container": "#1a1b41"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
